parameters:
    - name: serviceConnection
      type: string
    - name: subscriptionId
      type: string
    - name: applicationName
      type: string
    - name: deploymentLocation
      type: string
      default: westeurope
    - name: pireanstorageaccountname
      type: string
    - name: projectId
      type: string
      default: s141
    - name: environmentId
      type: string
    - name: environmentName
      type: string
    - name: servicePlanSkuName
      type: string
      default: Y1
    - name: sevicePlanSkuTier
      type: string
      default: Dynamic
    - name: topicName
      type: string
      default: audit
    - name: platformVariableGroupName
      type: string
    - name: shdResourceGroup
      type: string
jobs:
- deployment: 'deploy_${{parameters.environmentName}}'
  displayName: 'Deploy [${{parameters.environmentName}}]'
  environment: '${{parameters.environmentName}}'
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: '${{parameters.platformVariableGroupName}}'
  - name: resourceGroupName
    value: '${{parameters.projectId}}${{parameters.environmentId}}-dataimport'
  - name: storageaccountimport
    value: tolower(concat(parameters('projectId'), parameters('environmentId'), parameters('serviceName'),'dataimport'))
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - download: current
          artifact: $(Build.BuildId)

        - task: AzurePowerShell@5
          displayName: Create Subnets
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            ScriptType: 'FilePath'
            ScriptPath: ./powershell/Add-Subnet-to-Existing-Vnet.ps1
            ScriptArguments: '-vNetName $(vnetname) -resourceGroupName $(vnetresourcegroupname) -AddressPrefixStorage $(vnetsubnetaddressprefixst) -AddressPrefixFunction $(vnetsubnetaddressprefixfa) -subnetNameStorage $(vnetsubnetnamest) -subnetNameFunction $(vnetsubnetnamefa)'
            azurePowerShellVersion: 'LatestVersion'
            pwsh: true

        - template: /Infrastructure/steps/deployment-template.yml@devopsTemplates
          parameters:
            serviceConnection: '${{parameters.serviceConnection}}'
            subscriptionId: '${{parameters.subscriptionId}}'
            resourceGroupName: '$(resourceGroupName)'
            location: '${{parameters.deploymentLocation}}'
            tags: $(Tags)
            shdResourceGroup: '${{parameters.shdResourceGroup}}'
            templateFilePath: $(Build.SourcesDirectory)/templates/functionapps/arm/idams-function-template.json
            storageAccountTemplateFilePath: $(Build.SourcesDirectory)/templates/functionapps/arm/storage-account-template.json 
            armParameterOverrideString: '-templatesBaseUri "$(templatesBaseUri)" -applicationName "${{parameters.applicationName}}" -environmentName "${{parameters.environmentName}}" -dirDBName "$(dirSqlDbName)" -dirDBHostName "$(dirSqlHostName)" -dirDBUsername "$(dirSqlLogin)" -dirDBPassword "$(dirSqlPassword)" -orgDBName "$(organisationsdbName)" -orgDBHostName "$(organisationsSqlHostName)" -orgDBUsername "$(organisationsdbUserName)" -orgDBPassword "$(organisationsdbPassword)" -idamsblobstorageconnectionstring "$(idamsblobstorageconnectionstring)" -environmentId "${{parameters.environmentId}}" -AppServicePlanSku "$(FunctionAppServicePlanSku)" -sharedResourceGroupName "$(sharedResourceGroupName)" -ppapiendpointurl "$(ppapiendpointurl)" -ppapifunctionkey "$(ppapifunctionkey)" '
            storageAccountParameterOverideString: '-applicationName "${{parameters.applicationName}}" -environmentId "${{parameters.environmentId}}"'
            processOutputs: true
              

        - task: AzurePowerShell@5
          displayName: Configure VNET Firewall rules for the Storage Account
          inputs:
            azureSubscription: ${{parameters.serviceConnection}}
            ScriptType: 'FilePath'
            ScriptPath: ./powershell/Configure-VNET-Firewall-Rules.ps1
            ScriptArguments: '-vNetName $(vnetname) -resourceGroupName $(vnetresourcegroupname) -AddressPrefix $(vnetsubnetaddressprefixst) -subnetName $(vnetsubnetnamest) -storageaccountName $(storageaccountimport) -storageaccountRGName $(resourceGroupName)'
            azurePowerShellVersion: 'LatestVersion'
            pwsh: true
     
        - task: AzurePowerShell@5
          displayName: Create Attachments Container
          inputs:
            azureSubscription: '${{parameters.serviceConnection}}'
            ScriptType: 'FilePath'
            scriptPath: './powershell/Container.ps1'
            ScriptArguments: '-StorageAccountName ${{parameters.pireanstorageaccountname}} -ContainerName "attachments"'
            azurePowerShellVersion: 'LatestVersion'
            pwsh: true

        - task: ExtractFiles@1
          displayName: Extract Build Artifact
          inputs:
            archiveFilePatterns: ../**/$(Build.BuildId).zip
            destinationFolder: artifactoutput
            cleanDestinationFolder: true

        - pwsh: |
            Write-Host "functionName is: $env:ARMOUTPUTS_ARMOUTPUT_FUNCTIONNAME"
            Write-Host "##vso[task.setvariable variable=functionName]$env:ARMOUTPUTS_ARMOUTPUT_FUNCTIONNAME"
        
        - task: replacetokens@3
          displayName: Tokenise Function.json
          inputs:
            targetFiles: '**/artifactoutput/**/function.json'
            encoding: auto
            writeBOM: true
            escapeType: json
            verbosity: detailed
            actionOnMissing: fail
            keepToken: false
            tokenPrefix: __
            tokenSuffix: __
            useLegacyPattern: false
            enableTelemetry: false

        - pwsh: |
            Get-ChildItem -Path $(Pipeline.Workspace) –Recurse
          displayName: Tidy up package in Pipeline workspace

        - task: ArchiveFiles@2
          displayName: Create package for Azure Function
          inputs:
            rootFolderOrFile: $(Pipeline.Workspace)/s/artifactoutput
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Pipeline.Workspace)/s/Function_$(Build.BuildId).zip
            replaceExistingArchive: true
            verbose: true

        - task: AzureFunctionApp@1
          displayName: Deploy Azure Function App
          inputs:
            azureSubscription: '${{parameters.serviceConnection}}'
            appType: functionApp
            deploymentMethod: zipDeploy
            appName: $(functionName)
            package: $(Pipeline.Workspace)/s/Function_$(Build.BuildId).zip