# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(DevServiceConnection)
    action: 'Create or Update Resource Group'
    resourceGroupName: 's141d02-pirean-logicapps'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)\**\LogicApp.parameters.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)\**\LogicApp.parameters.json'
    overrideParameters: '-logicAppName IDAMS-ImportApp'
    deploymentMode: 'Incremental'