name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: platform-global

stages:
 - template: /templates/stages/pirean-master-logicapp-stage.yml@devopsTemplates
   parameters:
     applicationName: idamsdsiapp
    
      