name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)project$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.idams-dsi-migration
      ref: master
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: pirean-global
- name: applicationName
  value: dataimport

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /templates/functionapps/jobs/pirean-master-functionapp-build-job.yml



    
      