name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)project$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.idams-dsi-migration
      ref: master
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: pirean-global
- name: applicationName
  value: dataimport

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /templates/functionapps/jobs/pirean-master-functionapp-build-job.yml


- stage: deployDevD01
  displayName: Deploy Dev D01
  variables:
   -group: pirean-dev           
  dependsOn: build
  jobs:
    - template: /templates/functionapps/jobs/pirean-master-deploy-infrastructure-idams-job.yml
      parameters:
        serviceConnection: $(devServiceConnection)
        subscriptionId: $(devSubscriptionId)
        pireanstorageaccountname: $(pireanstorageaccountname)
        applicationName: $(applicationName)
        environmentId: d01
        environmentName: dev
        shdResourceGroup: s141d01-shd
        platformVariableGroupName: pirean-dev
        platformIdamsVariableGroupName: pirean-dev-idamsdsiapp

- stage: deployTestT01
  displayName: Deploy Test T01
  variables:
   -group: pirean-Test
           
  dependsOn: deployDevD01
  jobs:
    - template: /templates/functionapps/jobs/pirean-master-deploy-infrastructure-idams-job.yml
      parameters:
        serviceConnection: $(testServiceConnection)
        subscriptionId: $(testSubscriptionId)
        pireanstorageaccountname: $(pireanstorageaccountname)
        applicationName: $(applicationName)
        environmentId: t01
        environmentName: test
        shdResourceGroup: s141t01-shd
        platformVariableGroupName: pirean-test
        platformIdamsVariableGroupName: pirean-test-idamsdsiapp

- stage: deployPPT02
  displayName: Deploy PP T02
  variables:
   -group: pirean-PP
           
  dependsOn: deployTestT01
  jobs:
    - template: /templates/functionapps/jobs/pirean-master-deploy-infrastructure-idams-job.yml
      parameters:
        serviceConnection: $(testServiceConnection)
        subscriptionId: $(testSubscriptionId)
        pireanstorageaccountname: $(pireanstorageaccountname)
        applicationName: $(applicationName)
        environmentId: t02
        environmentName: pp
        shdResourceGroup: s141t02-shd
        platformVariableGroupName: pirean-pp
        platformIdamsVariableGroupName: pirean-pp-idamsdsiapp
    
      