name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.idams-dsi-migration
      ref: master
trigger:
- master

pool:
  vmImage: 'windows-latest'

pr: none

variables:
- name: artifactName
  value: deploy_artifacts
- name: devEnvironment
  value: dev
- name: applicationName
  value: idamsdsiapp 
- group: platform-global

stages:
- stage: Builds
  displayName: 'Publish IaC Artifacts'
  variables:
   -group: platform-dev
           platform-global
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: CopyFiles@2
      displayName: 'Copy ARM templates'
      inputs:
        sourceFolder: '$(System.DefaultWorkingDirectory)/templates/logicapps/deploy/'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: $(artifactName)

    - task: AzureFileCopy@4
      displayName: 'Copy Workflow and Connectors to Azure Storage'
      inputs:
        SourcePath: $(Build.ArtifactStagingDirectory)/templates/logicapps/deploy/
        azureSubscription: $(devServiceConnection)
        Destination: AzureBlob
        storage: s141d02logicappstorage
        ContainerName: idamsdsiappcontainer

- stage: DEV
  displayName: 'DEV Deployment'
  variables:
    - group: platform-global
  jobs:
  - template: /templates/logicapps/template-iac-logicapp.yml
    parameters:
      serviceConnection: $(devServiceConnection)
      environment: dev
      environmentId: d02
      variableGroups:
            -  platform-dev
            -  platform-global
            - "platform-dev-${{variables.applicationName}}"
      
    
    