name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.idams-dsi-migration
      ref: master
trigger:
- none

pool:
  vmImage: 'windows-latest'

pr: none

variables:
- name: artifactName
  value: deploy_artifacts
- name: devEnvironment
  value: dev
- name: applicationName
  value: idamsdsiapp 

stages:
- stage: Builds
  displayName: 'Publish IaC Artifacts'
  variables:
   -group: platform-dev
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-18.04
    steps:
    - task: CopyFiles@2
      displayName: 'Copy ARM templates'
      inputs:
        sourceFolder: '/templates/logicapps/deploy'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: $(artifactName)

- stage: DEV
  displayName: 'DEV Deployment'
  variables:
    - group: platform-global
  jobs:
  - template: /templates/logicapps/template-iac-logicapp.yml
    parameters:
      serviceConnection: $(devServiceConnection)
      environment: dev
      variableGroups:
            -  platform-dev
            -  platform-global
            - "platform-dev-${{variables.applicationName}}"
      
    
    