name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.idams-dsi-migration
      ref: master
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: pirean-global
- group: pirean-dev
- group: pirean-dev-idamsdsiapp

stages:


- stage: deployDevD01
  displayName: Deploy Dev D01
  variables:
   -group: pirean-dev      
  jobs:
    - template: /templates/infrastructure/pirean-master-deploy-infrastructure.yml
      parameters:
        serviceConnection: $(devServiceConnection)
        subscriptionId: $(devSubscriptionId)
        pireanstorageaccountname: $(pireanstorageaccountname)
        environmentId: d01
        environmentName: dev
        shdResourceGroup: s141d01-shd
        platformVariableGroupName: pirean-dev
        platformIdamsVariableGroupName: pirean-dev-idamsdsiapp
        templateFilePath: $(Build.SourcesDirectory)/templates/infrastructure/privatelinkscope.json
        armParameterOverrideString: '-templatesBaseUri "$(templatesBaseUri)" -environmentName "${{parameters.environmentName}}" -dirDBName "$(dirSqlDbName)" -dirDBHostName "$(dirSqlHostName)" -dirDBUsername "$(dirSqlLogin)" -dirDBPassword "$(dirSqlPassword)" -orgDBName "$(organisationsdbName)" -orgDBHostName "$(organisationsSqlHostName)" -orgDBUsername "$(organisationsdbUserName)" -orgDBPassword "$(organisationsdbPassword)" -idamsblobstorageconnectionstring "$(idamsblobstorageconnectionstring)" -environmentId "${{parameters.environmentId}}" -AppServicePlanSku "$(FunctionAppServicePlanSku)" -sharedResourceGroupName "${{parameters.shdResourceGroup}}" -ppapiendpointurl "$(ppapiendpointurl)" -ppapifunctionkey "$(ppapifunctionkey)" '
        processOutputs: true
    
- stage: deployTestT01
  displayName: Deploy Test T01
  variables:
   -group: pirean-Test
           
  dependsOn: deployDevD01
  jobs:
   - template: /templates/infrastructure/pirean-master-deploy-infrastructure.yml
     parameters:
        serviceConnection: $(testServiceConnection)
        subscriptionId: $(testSubscriptionId)
        pireanstorageaccountname: $(pireanstorageaccountname)
        environmentId: t01
        environmentName: test
        shdResourceGroup: s141t01-shd
        platformVariableGroupName: pirean-test
        platformIdamsVariableGroupName: pirean-test-idamsdsiapp
        templateFilePath: $(Build.SourcesDirectory)/templates/infrastructure/privatelinkscope.json
        # armParameterOverrideString: '-templatesBaseUri "$(templatesBaseUri)" -environmentName "${{parameters.environmentName}}"  -environmentId "${{parameters.environmentId}}" -sharedResourceGroupName "${{parameters.shdResourceGroup}}" '
        processOutputs: true