name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: self
      persistCredentials: true
      clean: true
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.idams-dsi-migration
      ref: master

variables:
- group: platform-global
- group: platform-Dev
- group: platform-dev-idamsdsiapp

stages:
- stage: importorgsdb
  displayName: Import Organisations Database
  jobs:
    - deployment: importorgsdb
      displayName: Import Organisations Database
      pool:
        vmImage: ubuntu-latest
      environment: 'dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self
              - checkout: devopsTemplates
              - task: AzureCLI@2
                displayName: 'Azure CLI - Promote Service Principal'
                inputs:
                  azureSubscription: 's141d-Pirean.azdo-deployment'
                  scriptType: pscore
                  scriptLocation: inlineScript
                  inlineScript: |
                  
                    Write-Host "##vso[task.setvariable variable=ARM_CLIENT_ID]$env:servicePrincipalId"
                    Write-Host "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$env:servicePrincipalKey"
                    Write-Host "##vso[task.setvariable variable=ARM_TENANT_ID]$env:tenantId"
                    Write-Host "##vso[task.setvariable variable=SQL_USER_NAME]$env:$organisationsdbUserName"
                  addSpnToEnvironment: true
              - task: AzurePowerShell@5
                displayName: Connect with Az
                inputs:
                  azureSubscription: 's141d-Pirean.azdo-deployment'
                  ScriptType: InlineScript
                  Inline: |
                 
                   $username = "$(ARM_CLIENT_ID)"
                   $password = "$(ARM_CLIENT_SECRET)"
                   $tenantId = "$(ARM_TENANT_ID)"
                   $sqlusername = "$(SQL_USER_NAME)"
                   Write-Host "SQL Login:" $sqlusername
                   az login --service-principal --username  $username --password $password --tenant $tenantId

                  azurePowerShellVersion: 'LatestVersion'                
                  
            
              - task: AzurePowerShell@5
                displayName: Import Organisations Database
                inputs:
                  azureSubscription: 's141d-Pirean.azdo-deployment'
                  ScriptType: 'FilePath'
                  ScriptPath: ./login.dfe.idams-dsi-migration/powershell/Import-from-bacpac-to-sql-db.ps1
                  ScriptArguments: '-resourceGroupName s141d02-shd -serverName $(organisationsSqlHostName) -databaseName $(organisationsdbName) -storageAccountName $(azureblobaccountname) -storageContainerName $(blobsqlcontainername) -bacpacFilename $(azureblobbacpacfilename) -adminSqlLogin $(organisationsdbUserName) -adminpwd $(organisationsdbPassword)'
                  azurePowerShellVersion: 'LatestVersion'
                  pwsh: true
     