parameters:
  - name: applicationName
    type: string
  - name: devServiceConnection
    type: string
    default: s141d-Pirean.azdo-deployment
  - name: devSubscriptionId
    type: string
    default: 9d98d71c-7399-47fc-a888-d5ea74c3d8c0

stages:
  - stage: build
    displayName: Build
    jobs:
      - template: ../jobs/pirean-master-logicapp-build-job.yml
        

  - stage: deployDev
    displayName: "Package & Deploy [DEV]"
    dependsOn: build
    jobs:
        - template: ../jobs/pirean-master-deploy-infrastructure-job.yml
          parameters:
            applicationName: ${{parameters.applicationName}}
            environmentName: dev
            environmentId: d01
            location: westeurope
            variableGroups:
              - pirean-dev
              - "pirean-dev-${{parameters.applicationName}}"
            serviceConnection: "$(devServiceConnection)"
            subscriptionId: "${{parameters.devSubscriptionId}}"

  - stage: deployTest
    displayName: "Package & Deploy [TEST]"
    dependsOn: deployDev
    jobs:
        - template: ../jobs/pirean-master-deploy-infrastructure-job.yml
          parameters:
            applicationName: ${{parameters.applicationName}}
            environmentName: test
            environmentId: t01
            location: westeurope
            variableGroups:
              - pirean-test
              - "pirean-test-${{parameters.applicationName}}"
            serviceConnection:  $(testServiceConnection)
            subscriptionId: $(TestSubscriptionId)

  - stage: deployPP
    displayName: "Package & Deploy [Pre-Prod]"
    dependsOn: deployTest
    jobs:
        - template: ../jobs/pirean-master-deploy-infrastructure-job.yml
          parameters:
            applicationName: ${{parameters.applicationName}}
            environmentName: pp
            environmentId: t02
            location: westeurope
            variableGroups:
              - pirean-pp
              - "pirean-pp-${{parameters.applicationName}}"
            serviceConnection:  $(testServiceConnection)
            subscriptionId: $(TestSubscriptionId)
          
   