# IaC Logic App resources deployment template

parameters:
- name: environment
  type: string
- name: environmentId
  type: string
- name: serviceConnection
  type: string
- name: applicationName
  type: string
- name: variableGroups
  type: object

jobs:
- deployment: deploy_logicapp_resources
  displayName: Deploy Logic App Resources
  pool:
    vmImage: 'windows-latest'
  environment: ${{ parameters.environment }}
  variables: 
  - '${{ each variableGroup in parameters.variableGroups }}':
    - group: '${{variableGroup}}'
  - name: applicationResourceGroupName
    value: '$(platformGlobalIdentifier)${{parameters.environmentId}}-${{parameters.applicationName}}' 
  - name: StorageAccountName
    value: '$(platformGlobalIdentifier)${{parameters.environmentId}}${{parameters.applicationName}}'
  - name: idamsdsifileshare
    value: '$(logicappname)'
  
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: $(artifactName)

        - task: AzureResourceGroupDeployment@2
          displayName: 'Deploy Logic App'
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            resourceGroupName: '$(applicationResourceGroupName)'
            
            location: 'westeurope'
            csmFile: '$(Pipeline.Workspace)/$(artifactName)/classic/logicapp-template.json'
            overrideParameters: '
              -logicAppLocation $(logicapplocation)
              -environmentName ${{ parameters.environment }}
              -projectName $(projectName)
              -logicAppName $(logicappname)
              -appServicePlanName "idamsdsiapp-asp"
              -storageName $(StorageAccountName)'
              
            deploymentMode: $(deploymentMode)
            deploymentOutputs: 'LogicAppArmOutputs'

        - task: ARM Outputs@6
          displayName: 'ARM Outputs'
          inputs:
            ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
            ConnectedServiceNameARM: ${{ parameters.serviceConnection }}
            resourceGroupName: '$(applicationResourceGroupName)'
            whenLastDeploymentIsFailed: 'fail'

               
        - task: AzurePowerShell@5
          displayName: Create Workflow and Connectors 
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            ScriptType: 'FilePath'
            ScriptPath: '$(Build.ArtifactStagingDirectory)/Create-Workflow-And-Connectors.ps1'
            ScriptArguments: '-applicationResourceGroupName $applicationResourceGroupName -StorageAccountName $StorageAccountName -idamsdsifileshare $idamsdsifileshare -logicappname $logicappname -artifactName $artifactName'
            azurePowerShellVersion: 'LatestVersion'
            pwsh: true
        - task: AzureCLI@2
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az functionapp config appsettings set --name $(LAname) --resource-group  "s141d02-idamsdsiapp" --settings "BLOB_CONNECTION_RUNTIMEURL=$(idamsblobstorageconnectionstring)"
              az functionapp config appsettings set --name $(LAname) --resource-group  "s141d02-idamsdsiapp" --settings "WORKFLOWS_RESOURCE_GROUP_NAME=s141d02-idamsdsiapp"
            addSpnToEnvironment: true
            useGlobalConfig: true